/**
 * Author: Aaron Woods
 */

#ifndef GENERATOR_H
#define GENERATOR_H

#include "bison-parser.h"
/**
 * This function is used to begin asm code
 * generation after the parser has completed
 * parsing the input file.
 *
 * @param prog the TreeProg containing the parse
 * 	           tree generated by the parser
 */
int generate(TreeProg prog);

#endif /* GENERATOR_H */
